//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersTbl
    {
        public long AnswerID { get; set; }
        public long QuestionID { get; set; }
        public long TeacherID { get; set; }
        public string Answer { get; set; }
        public System.DateTime AnsweredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual QuestionTbl QuestionTbl { get; set; }
        public virtual TeacherTbl TeacherTbl { get; set; }
    }
}
