//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionTbl()
        {
            this.AnswersTbls = new HashSet<AnswersTbl>();
        }
    
        public long QuestID { get; set; }
        public long StudentID { get; set; }
        public string Question { get; set; }
        public System.DateTime AskedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTbl> AnswersTbls { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
