//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyMaterialTbl
    {
        public long MaterialID { get; set; }
        public long StudentID { get; set; }
        public Nullable<long> TeacherID { get; set; }
        public string MaterialName { get; set; }
        public string MaterialDetails { get; set; }
        public string MaterilaLink { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual StudentTbl StudentTbl { get; set; }
        public virtual TeacherTbl TeacherTbl { get; set; }
    }
}
