//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersStudentTbl
    {
        public long TeachersStudentId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<long> TeacherId { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    }
}
