//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTbl()
        {
            this.AnswersTbls = new HashSet<AnswersTbl>();
            this.StudyMaterialTbls = new HashSet<StudyMaterialTbl>();
            this.TeachersStudentTbls = new HashSet<TeachersStudentTbl>();
            this.RateTbls = new HashSet<RateTbl>();
        }
    
        public long TeacherID { get; set; }
        public long CredID { get; set; }
        public string FullName { get; set; }
        public string Location { get; set; }
        public System.DateTime EnterdOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string DOB { get; set; }
        public Nullable<bool> IsOffline { get; set; }
        public string OfflineTime { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string OnlineTime { get; set; }
        public string Days { get; set; }
        public string DemoClassURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string HighestEducation { get; set; }
        public string Certificate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTbl> AnswersTbls { get; set; }
        public virtual CredentialTbl CredentialTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyMaterialTbl> StudyMaterialTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeachersStudentTbl> TeachersStudentTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateTbl> RateTbls { get; set; }
    }
}
