//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTbl()
        {
            this.AnswersTbls = new HashSet<AnswersTbl>();
        }
    
        public long TeacherID { get; set; }
        public long CredID { get; set; }
        public string FullName { get; set; }
        public string Location { get; set; }
        public System.DateTime EnterdOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTbl> AnswersTbls { get; set; }
        public virtual CredentialTbl CredentialTbl { get; set; }
    }
}
